before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build cs112S2018_syllabus.tex
deploy:
  provider: releases
  api_key:
    secure: jvBWFqeT/4Tc8NuGESGAo7uy6Ih+HDERRVeB22BH2mXgOYUtZIPhK6U4fGQjPuIvsY4Z54ZNwUZfPK2jA2P+lapvf206TGJAfDqZSHgIYJwrVPTRKwCtfocOxhmyzEh//N1/JUIw0rjnp6x0vooto5DNmKQ/B9vv2hjyr0F9mi1o9H1Q0nG3k+nXR2NXOembnAYeSYUSW1lCZuFIQwM5UCdBrFkWnHcEL7vgpK/RORlj48tmNetwpdfx90+RwR1vsNUxtXRforBjTuIaclqEy3EJplau1d8xMEN1y8Y/b8+thQ/CXoOi/u+MdPGZzy+Mzaesj/0cjUQ3V6HgRdvcTijDUVL9GPWwb0guZf1Jg1fVtkgRt96TZpi05UkpVA4Ys5TZzBAex5E9QdG10loLDqYXbn6+v6JhWRAy3bbsm4EDYkOy/XkTqW8HhKQChiwO/C/nbWYUZ9pSvaAqJuH9DgKhMqIiWMvhbs+RVQBLRazjfMe/3W8tyQKNDSlmwpnCjSzopbpcjGm51E1+fcL/dEF6WCluv+/Q4m0II0x7d0L4M9rD53W1nihKEticQ8enKc5sP6mtEBZ9fi0ORANHDeZeX9Wmxv+Tk7LbOzDDQiAH2D0nPo3kstP7ETnySTKLNMh4Fienvvfkl9qkSw/StCBCC3gtfpCiqxG+DVdsg5w=
  file: _build/cs112S2018_syllabus.pdf
  skip_cleanup: true
  on:
    tags: true
